[package]
name = "acceptevm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
sled = "0.34.7"
thiserror = "1.0.59"
web3 = "0.19.0"
