[package]
name = "acceptevm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alloy = { git = "https://github.com/alloy-rs/alloy", version = "0.1.0",features=["signers","signer-wallet"] }
bincode = "1.3.3"
sled = "0.34.7"
thiserror = "1.0.59"
web3 = "0.19.0"
serde = { version="1.0.197",features=["derive"] }
sha2 = "0.10.8"
tokio = "1.37.0"
